spring:
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect


  datasource:
    initialization-mode: always
    url: jdbc:mysql://team1-poc-an2-db-mysql.cluster-ckfkoizozxni.ap-northeast-2.rds.amazonaws.com/customer
    username: admin
    password: admin!234
    driver-class-name: com.mysql.cj.jdbc.Driver
    #schema: classpath*:db/mysql/schema.sql
