spring:
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect


  datasource:
    initialization-mode: always
    url: jdbc:mysql://{AWS DB ENDPOINT}:3306/customer
    username: {AWS DB ID}
    password: {AWS DB PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
    #schema: classpath*:db/mysql/schema.sql
